add_test([=[EllipticCurve.isOnCurve]=]  /home/cat/longfellow-zk/build-verifier/ec/elliptic_curve_test [==[--gtest_filter=EllipticCurve.isOnCurve]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EllipticCurve.isOnCurve]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/ec SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EllipticCurve.addEZeroA]=]  /home/cat/longfellow-zk/build-verifier/ec/elliptic_curve_test [==[--gtest_filter=EllipticCurve.addEZeroA]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EllipticCurve.addEZeroA]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/ec SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EllipticCurve.doubleEZeroA]=]  /home/cat/longfellow-zk/build-verifier/ec/elliptic_curve_test [==[--gtest_filter=EllipticCurve.doubleEZeroA]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EllipticCurve.doubleEZeroA]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/ec SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EllipticCurve.addEMinus3A]=]  /home/cat/longfellow-zk/build-verifier/ec/elliptic_curve_test [==[--gtest_filter=EllipticCurve.addEMinus3A]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EllipticCurve.addEMinus3A]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/ec SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EllipticCurve.doubleEMinus3A]=]  /home/cat/longfellow-zk/build-verifier/ec/elliptic_curve_test [==[--gtest_filter=EllipticCurve.doubleEMinus3A]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EllipticCurve.doubleEMinus3A]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/ec SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EllipticCurve.addEGeneral]=]  /home/cat/longfellow-zk/build-verifier/ec/elliptic_curve_test [==[--gtest_filter=EllipticCurve.addEGeneral]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EllipticCurve.addEGeneral]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/ec SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EllipticCurve.doubleEGeneral]=]  /home/cat/longfellow-zk/build-verifier/ec/elliptic_curve_test [==[--gtest_filter=EllipticCurve.doubleEGeneral]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EllipticCurve.doubleEGeneral]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/ec SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EllipticCurve.P256MultiExponentiation]=]  /home/cat/longfellow-zk/build-verifier/ec/elliptic_curve_test [==[--gtest_filter=EllipticCurve.P256MultiExponentiation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EllipticCurve.P256MultiExponentiation]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/ec SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EllipticCurve.P256k1MultiExponentiation]=]  /home/cat/longfellow-zk/build-verifier/ec/elliptic_curve_test [==[--gtest_filter=EllipticCurve.P256k1MultiExponentiation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EllipticCurve.P256k1MultiExponentiation]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/ec SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  elliptic_curve_test_TESTS EllipticCurve.isOnCurve EllipticCurve.addEZeroA EllipticCurve.doubleEZeroA EllipticCurve.addEMinus3A EllipticCurve.doubleEMinus3A EllipticCurve.addEGeneral EllipticCurve.doubleEGeneral EllipticCurve.P256MultiExponentiation EllipticCurve.P256k1MultiExponentiation)
