if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/logic/counter_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/logic/counter_test[1]_tests.cmake")
else()
  add_test(counter_test_NOT_BUILT counter_test_NOT_BUILT)
endif()
