if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/logic/memcmp_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/logic/memcmp_test[1]_tests.cmake")
else()
  add_test(memcmp_test_NOT_BUILT memcmp_test_NOT_BUILT)
endif()
