if(EXISTS "/home/cat/longfellow-zk/build-bringup/circuits/tests/ripemd/ripemd_circuit_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-bringup/circuits/tests/ripemd/ripemd_circuit_test[1]_tests.cmake")
else()
  add_test(ripemd_circuit_test_NOT_BUILT ripemd_circuit_test_NOT_BUILT)
endif()
