if(EXISTS "/home/cat/longfellow-zk/build-demo-cli/circuits/cbor_parser/scan_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-demo-cli/circuits/cbor_parser/scan_test[1]_tests.cmake")
else()
  add_test(scan_test_NOT_BUILT scan_test_NOT_BUILT)
endif()
