add_test([=[MerkleTree.BuildTree]=]  /home/cat/longfellow-zk/clang-build-release/merkle/merkle_tree_test [==[--gtest_filter=MerkleTree.BuildTree]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MerkleTree.BuildTree]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/merkle SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MerkleTree.VerifyCompressedProof]=]  /home/cat/longfellow-zk/clang-build-release/merkle/merkle_tree_test [==[--gtest_filter=MerkleTree.VerifyCompressedProof]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MerkleTree.VerifyCompressedProof]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/merkle SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MerkleTree.VerifyCompressedProofFailure]=]  /home/cat/longfellow-zk/clang-build-release/merkle/merkle_tree_test [==[--gtest_filter=MerkleTree.VerifyCompressedProofFailure]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MerkleTree.VerifyCompressedProofFailure]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/merkle SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MerkleTree.ZeroLengthProof]=]  /home/cat/longfellow-zk/clang-build-release/merkle/merkle_tree_test [==[--gtest_filter=MerkleTree.ZeroLengthProof]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MerkleTree.ZeroLengthProof]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/merkle SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MerkleTree.UniqueLeaves]=]  /home/cat/longfellow-zk/clang-build-release/merkle/merkle_tree_test [==[--gtest_filter=MerkleTree.UniqueLeaves]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MerkleTree.UniqueLeaves]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/merkle SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MerkleTree.BatchVerifyProofTooShort]=]  /home/cat/longfellow-zk/clang-build-release/merkle/merkle_tree_test [==[--gtest_filter=MerkleTree.BatchVerifyProofTooShort]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MerkleTree.BatchVerifyProofTooShort]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/merkle SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MerkleTree.TestVectors]=]  /home/cat/longfellow-zk/clang-build-release/merkle/merkle_tree_test [==[--gtest_filter=MerkleTree.TestVectors]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MerkleTree.TestVectors]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/merkle SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  merkle_tree_test_TESTS MerkleTree.BuildTree MerkleTree.VerifyCompressedProof MerkleTree.VerifyCompressedProofFailure MerkleTree.ZeroLengthProof MerkleTree.UniqueLeaves MerkleTree.BatchVerifyProofTooShort MerkleTree.TestVectors)
