if(EXISTS "/home/cat/longfellow-zk/clang-build-release/merkle/merkle_tree_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/clang-build-release/merkle/merkle_tree_test[1]_tests.cmake")
else()
  add_test(merkle_tree_test_NOT_BUILT merkle_tree_test_NOT_BUILT)
endif()
