if(EXISTS "/Users/cnxf/信安赛/代理签名/translated_atrps/code/longfellow-zk/build-delegation/gf2k/lch14_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/代理签名/translated_atrps/code/longfellow-zk/build-delegation/gf2k/lch14_test[1]_tests.cmake")
else()
  add_test(lch14_test_NOT_BUILT lch14_test_NOT_BUILT)
endif()
