if(EXISTS "/Users/cnxf/信安赛/代理签名/translated_atrps/code/longfellow-zk/build-delegation/circuits/ecdsa/verify_external_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/代理签名/translated_atrps/code/longfellow-zk/build-delegation/circuits/ecdsa/verify_external_test[1]_tests.cmake")
else()
  add_test(verify_external_test_NOT_BUILT verify_external_test_NOT_BUILT)
endif()
