if(EXISTS "/home/cat/longfellow-zk/build-demo-cli/zk/zk_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-demo-cli/zk/zk_test[1]_tests.cmake")
else()
  add_test(zk_test_NOT_BUILT zk_test_NOT_BUILT)
endif()
