if(EXISTS "/home/cat/longfellow-zk/build-demo-cli/algebra/fp_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-demo-cli/algebra/fp_test[1]_tests.cmake")
else()
  add_test(fp_test_NOT_BUILT fp_test_NOT_BUILT)
endif()
