if(EXISTS "/home/cat/longfellow-zk/build-demo-cli/algebra/limb_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-demo-cli/algebra/limb_test[1]_tests.cmake")
else()
  add_test(limb_test_NOT_BUILT limb_test_NOT_BUILT)
endif()
