if(EXISTS "/home/cat/longfellow-zk/build-demo-cli/algebra/nat_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-demo-cli/algebra/nat_test[1]_tests.cmake")
else()
  add_test(nat_test_NOT_BUILT nat_test_NOT_BUILT)
endif()
