if(EXISTS "/home/cat/longfellow-zk/build-demo-cli/algebra/rfft_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-demo-cli/algebra/rfft_test[1]_tests.cmake")
else()
  add_test(rfft_test_NOT_BUILT rfft_test_NOT_BUILT)
endif()
