if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/cbor_parser/mso_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/cbor_parser/mso_test[1]_tests.cmake")
else()
  add_test(mso_test_NOT_BUILT mso_test_NOT_BUILT)
endif()
