if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/cbor_parser/scan_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/cbor_parser/scan_test[1]_tests.cmake")
else()
  add_test(scan_test_NOT_BUILT scan_test_NOT_BUILT)
endif()
