if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/arrays/eqs_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/arrays/eqs_test[1]_tests.cmake")
else()
  add_test(eqs_test_NOT_BUILT eqs_test_NOT_BUILT)
endif()
