if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/sumcheck/quad_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/sumcheck/quad_test[1]_tests.cmake")
else()
  add_test(quad_test_NOT_BUILT quad_test_NOT_BUILT)
endif()
