add_test([=[Nat.Lt]=]  /home/cat/longfellow-zk/clang-build-release/algebra/nat_test [==[--gtest_filter=Nat.Lt]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Nat.Lt]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Nat.InvModB64]=]  /home/cat/longfellow-zk/clang-build-release/algebra/nat_test [==[--gtest_filter=Nat.InvModB64]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Nat.InvModB64]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Nat.InvModB32]=]  /home/cat/longfellow-zk/clang-build-release/algebra/nat_test [==[--gtest_filter=Nat.InvModB32]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Nat.InvModB32]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Nat.Parsing]=]  /home/cat/longfellow-zk/clang-build-release/algebra/nat_test [==[--gtest_filter=Nat.Parsing]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Nat.Parsing]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Nat.BadStrings]=]  /home/cat/longfellow-zk/clang-build-release/algebra/nat_test [==[--gtest_filter=Nat.BadStrings]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Nat.BadStrings]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Nat.BadDigits]=]  /home/cat/longfellow-zk/clang-build-release/algebra/nat_test [==[--gtest_filter=Nat.BadDigits]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Nat.BadDigits]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Nat.Mac]=]  /home/cat/longfellow-zk/clang-build-release/algebra/nat_test [==[--gtest_filter=Nat.Mac]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Nat.Mac]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  nat_test_TESTS Nat.Lt Nat.InvModB64 Nat.InvModB32 Nat.Parsing Nat.BadStrings Nat.BadDigits Nat.Mac)
