add_test([=[BitPlucker.PluckPrimeField]=]  /home/cat/longfellow-zk/clang-build-release/circuits/logic/bit_plucker_test [==[--gtest_filter=BitPlucker.PluckPrimeField]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BitPlucker.PluckPrimeField]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/circuits/logic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BitPlucker.PluckBinaryField]=]  /home/cat/longfellow-zk/clang-build-release/circuits/logic/bit_plucker_test [==[--gtest_filter=BitPlucker.PluckBinaryField]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BitPlucker.PluckBinaryField]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/circuits/logic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BitPlucker.PluckSizePrimeField]=]  /home/cat/longfellow-zk/clang-build-release/circuits/logic/bit_plucker_test [==[--gtest_filter=BitPlucker.PluckSizePrimeField]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BitPlucker.PluckSizePrimeField]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/circuits/logic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BitPlucker.PluckSizeBinaryField]=]  /home/cat/longfellow-zk/clang-build-release/circuits/logic/bit_plucker_test [==[--gtest_filter=BitPlucker.PluckSizeBinaryField]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BitPlucker.PluckSizeBinaryField]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/circuits/logic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BitPlucker.EltMuxer]=]  /home/cat/longfellow-zk/clang-build-release/circuits/logic/bit_plucker_test [==[--gtest_filter=BitPlucker.EltMuxer]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BitPlucker.EltMuxer]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/circuits/logic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BitPlucker.EltMuxer9]=]  /home/cat/longfellow-zk/clang-build-release/circuits/logic/bit_plucker_test [==[--gtest_filter=BitPlucker.EltMuxer9]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BitPlucker.EltMuxer9]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/circuits/logic SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  bit_plucker_test_TESTS BitPlucker.PluckPrimeField BitPlucker.PluckBinaryField BitPlucker.PluckSizePrimeField BitPlucker.PluckSizeBinaryField BitPlucker.EltMuxer BitPlucker.EltMuxer9)
