if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/gf2k/gf2_128_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/gf2k/gf2_128_test[1]_tests.cmake")
else()
  add_test(gf2_128_test_NOT_BUILT gf2_128_test_NOT_BUILT)
endif()
