if(EXISTS "/Users/cnxf/信安赛/代理签名/translated_atrps/code/longfellow-zk/build-delegation/cbor/host_decoder_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/代理签名/translated_atrps/code/longfellow-zk/build-delegation/cbor/host_decoder_test[1]_tests.cmake")
else()
  add_test(host_decoder_test_NOT_BUILT host_decoder_test_NOT_BUILT)
endif()
