add_test([=[HostDecoderTest.DecodeHost]=]  /home/cat/longfellow-zk/build-verifier/cbor/host_decoder_test [==[--gtest_filter=HostDecoderTest.DecodeHost]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HostDecoderTest.DecodeHost]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/cbor SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[HostDecoderTest.Lookup]=]  /home/cat/longfellow-zk/build-verifier/cbor/host_decoder_test [==[--gtest_filter=HostDecoderTest.Lookup]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[HostDecoderTest.Lookup]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/cbor SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  host_decoder_test_TESTS HostDecoderTest.DecodeHost HostDecoderTest.Lookup)
