if(EXISTS "/home/cat/longfellow-zk/build-demo-cli/circuits/ecdsa/verify_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-demo-cli/circuits/ecdsa/verify_test[1]_tests.cmake")
else()
  add_test(verify_test_NOT_BUILT verify_test_NOT_BUILT)
endif()
