if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/tests/anoncred/small_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/tests/anoncred/small_test[1]_tests.cmake")
else()
  add_test(small_test_NOT_BUILT small_test_NOT_BUILT)
endif()
