if(EXISTS "/home/cat/longfellow-zk/build-demo-cli/examples/mdoc_anoncred/mdoc_anoncred_demo_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-demo-cli/examples/mdoc_anoncred/mdoc_anoncred_demo_test[1]_tests.cmake")
else()
  add_test(mdoc_anoncred_demo_test_NOT_BUILT mdoc_anoncred_demo_test_NOT_BUILT)
endif()
