add_test([=[Morton.Even]=]  /home/cat/longfellow-zk/build-verifier/util/ceildiv_test [==[--gtest_filter=Morton.Even]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Morton.Even]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Morton.Uneven]=]  /home/cat/longfellow-zk/build-verifier/util/ceildiv_test [==[--gtest_filter=Morton.Uneven]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Morton.Uneven]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Morton.AddSub]=]  /home/cat/longfellow-zk/build-verifier/util/ceildiv_test [==[--gtest_filter=Morton.AddSub]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Morton.AddSub]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/util SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  ceildiv_test_TESTS Morton.Even Morton.Uneven Morton.AddSub)
