add_test([=[Compiler.OutputAnInput]=]  /home/cat/longfellow-zk/build-verifier/circuits/compiler/compiler_test [==[--gtest_filter=Compiler.OutputAnInput]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Compiler.OutputAnInput]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/compiler SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Compiler.AliasOfLinearAndCopyWire]=]  /home/cat/longfellow-zk/build-verifier/circuits/compiler/compiler_test [==[--gtest_filter=Compiler.AliasOfLinearAndCopyWire]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Compiler.AliasOfLinearAndCopyWire]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/compiler SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Compiler.Assert0]=]  /home/cat/longfellow-zk/build-verifier/circuits/compiler/compiler_test [==[--gtest_filter=Compiler.Assert0]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Compiler.Assert0]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/compiler SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Compiler.Output0]=]  /home/cat/longfellow-zk/build-verifier/circuits/compiler/compiler_test [==[--gtest_filter=Compiler.Output0]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Compiler.Output0]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/compiler SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  compiler_test_TESTS Compiler.OutputAnInput Compiler.AliasOfLinearAndCopyWire Compiler.Assert0 Compiler.Output0)
