add_test([=[GF2_128.Constants]=]  /home/cat/longfellow-zk/build-verifier/gf2k/gf2_128_test [==[--gtest_filter=GF2_128.Constants]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GF2_128.Constants]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GF2_128.Invert0]=]  /home/cat/longfellow-zk/build-verifier/gf2k/gf2_128_test [==[--gtest_filter=GF2_128.Invert0]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GF2_128.Invert0]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GF2_128.Invert1]=]  /home/cat/longfellow-zk/build-verifier/gf2k/gf2_128_test [==[--gtest_filter=GF2_128.Invert1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GF2_128.Invert1]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GF2_128.Cmp]=]  /home/cat/longfellow-zk/build-verifier/gf2k/gf2_128_test [==[--gtest_filter=GF2_128.Cmp]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GF2_128.Cmp]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GF2_128.Mul]=]  /home/cat/longfellow-zk/build-verifier/gf2k/gf2_128_test [==[--gtest_filter=GF2_128.Mul]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GF2_128.Mul]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GF2_128.PolyEvaluationPoint]=]  /home/cat/longfellow-zk/build-verifier/gf2k/gf2_128_test [==[--gtest_filter=GF2_128.PolyEvaluationPoint]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GF2_128.PolyEvaluationPoint]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GF2_128.EvalLagrange]=]  /home/cat/longfellow-zk/build-verifier/gf2k/gf2_128_test [==[--gtest_filter=GF2_128.EvalLagrange]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GF2_128.EvalLagrange]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GF2_128.Extend]=]  /home/cat/longfellow-zk/build-verifier/gf2k/gf2_128_test [==[--gtest_filter=GF2_128.Extend]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GF2_128.Extend]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GF2_128.X]=]  /home/cat/longfellow-zk/build-verifier/gf2k/gf2_128_test [==[--gtest_filter=GF2_128.X]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GF2_128.X]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GF2_128.Beta]=]  /home/cat/longfellow-zk/build-verifier/gf2k/gf2_128_test [==[--gtest_filter=GF2_128.Beta]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GF2_128.Beta]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GF2_128.OfScalar]=]  /home/cat/longfellow-zk/build-verifier/gf2k/gf2_128_test [==[--gtest_filter=GF2_128.OfScalar]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GF2_128.OfScalar]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GF2_128.SubFieldSize]=]  /home/cat/longfellow-zk/build-verifier/gf2k/gf2_128_test [==[--gtest_filter=GF2_128.SubFieldSize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GF2_128.SubFieldSize]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GF2_128.Counter]=]  /home/cat/longfellow-zk/build-verifier/gf2k/gf2_128_test [==[--gtest_filter=GF2_128.Counter]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GF2_128.Counter]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GF2_128.Bytes]=]  /home/cat/longfellow-zk/build-verifier/gf2k/gf2_128_test [==[--gtest_filter=GF2_128.Bytes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GF2_128.Bytes]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GF2_128.Subfields]=]  /home/cat/longfellow-zk/build-verifier/gf2k/gf2_128_test [==[--gtest_filter=GF2_128.Subfields]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GF2_128.Subfields]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/gf2k SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  gf2_128_test_TESTS GF2_128.Constants GF2_128.Invert0 GF2_128.Invert1 GF2_128.Cmp GF2_128.Mul GF2_128.PolyEvaluationPoint GF2_128.EvalLagrange GF2_128.Extend GF2_128.X GF2_128.Beta GF2_128.OfScalar GF2_128.SubFieldSize GF2_128.Counter GF2_128.Bytes GF2_128.Subfields)
