add_test([=[CrtTest.Fp256Test]=]  /home/cat/longfellow-zk/build-verifier/algebra/crt_test [==[--gtest_filter=CrtTest.Fp256Test]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CrtTest.Fp256Test]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CrtTest.Fp384Test]=]  /home/cat/longfellow-zk/build-verifier/algebra/crt_test [==[--gtest_filter=CrtTest.Fp384Test]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CrtTest.Fp384Test]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CrtTest.Fp521Test]=]  /home/cat/longfellow-zk/build-verifier/algebra/crt_test [==[--gtest_filter=CrtTest.Fp521Test]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CrtTest.Fp521Test]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CrtTest.RootOfUnity]=]  /home/cat/longfellow-zk/build-verifier/algebra/crt_test [==[--gtest_filter=CrtTest.RootOfUnity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CrtTest.RootOfUnity]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CrtTest.FFTInverse]=]  /home/cat/longfellow-zk/build-verifier/algebra/crt_test [==[--gtest_filter=CrtTest.FFTInverse]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CrtTest.FFTInverse]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CrtTest.ConvolutionTest]=]  /home/cat/longfellow-zk/build-verifier/algebra/crt_test [==[--gtest_filter=CrtTest.ConvolutionTest]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CrtTest.ConvolutionTest]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  crt_test_TESTS CrtTest.Fp256Test CrtTest.Fp384Test CrtTest.Fp521Test CrtTest.RootOfUnity CrtTest.FFTInverse CrtTest.ConvolutionTest)
