if(EXISTS "/home/cat/longfellow-zk/build-verifier/algebra/fft_interpolation_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-verifier/algebra/fft_interpolation_test[1]_tests.cmake")
else()
  add_test(fft_interpolation_test_NOT_BUILT fft_interpolation_test_NOT_BUILT)
endif()
