if(EXISTS "/home/cat/longfellow-zk/build-verifier/algebra/interpolation_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-verifier/algebra/interpolation_test[1]_tests.cmake")
else()
  add_test(interpolation_test_NOT_BUILT interpolation_test_NOT_BUILT)
endif()
