if(EXISTS "/home/cat/longfellow-zk/build-verifier/algebra/nussbaumerfp2_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-verifier/algebra/nussbaumerfp2_test[1]_tests.cmake")
else()
  add_test(nussbaumerfp2_test_NOT_BUILT nussbaumerfp2_test_NOT_BUILT)
endif()
