add_test([=[ReedSolomonTest.ReedSolomon]=]  /home/cat/longfellow-zk/build-verifier/algebra/reed_solomon_test [==[--gtest_filter=ReedSolomonTest.ReedSolomon]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ReedSolomonTest.ReedSolomon]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ReedSolomonTest.SlowConvolutionFactory]=]  /home/cat/longfellow-zk/build-verifier/algebra/reed_solomon_test [==[--gtest_filter=ReedSolomonTest.SlowConvolutionFactory]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ReedSolomonTest.SlowConvolutionFactory]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ReedSolomonTest.LowDegreePolynomial]=]  /home/cat/longfellow-zk/build-verifier/algebra/reed_solomon_test [==[--gtest_filter=ReedSolomonTest.LowDegreePolynomial]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ReedSolomonTest.LowDegreePolynomial]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ReedSolomonTest.FieldExtension]=]  /home/cat/longfellow-zk/build-verifier/algebra/reed_solomon_test [==[--gtest_filter=ReedSolomonTest.FieldExtension]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ReedSolomonTest.FieldExtension]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Reed_Solomon.Product]=]  /home/cat/longfellow-zk/build-verifier/algebra/reed_solomon_test [==[--gtest_filter=Reed_Solomon.Product]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Reed_Solomon.Product]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/algebra SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  reed_solomon_test_TESTS ReedSolomonTest.ReedSolomon ReedSolomonTest.SlowConvolutionFactory ReedSolomonTest.LowDegreePolynomial ReedSolomonTest.FieldExtension Reed_Solomon.Product)
