if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/tests/sha3/sha3_circuit_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/tests/sha3/sha3_circuit_test[1]_tests.cmake")
else()
  add_test(sha3_circuit_test_NOT_BUILT sha3_circuit_test_NOT_BUILT)
endif()
