if(EXISTS "/home/cat/longfellow-zk/build-demo-cli/circuits/tests/base64/decode_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-demo-cli/circuits/tests/base64/decode_test[1]_tests.cmake")
else()
  add_test(decode_test_NOT_BUILT decode_test_NOT_BUILT)
endif()
