if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/merkle/merkle_tree_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/merkle/merkle_tree_test[1]_tests.cmake")
else()
  add_test(merkle_tree_test_NOT_BUILT merkle_tree_test_NOT_BUILT)
endif()
