if(EXISTS "/home/cat/longfellow-zk/build-bringup/circuits/compiler/canonicalization_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-bringup/circuits/compiler/canonicalization_test[1]_tests.cmake")
else()
  add_test(canonicalization_test_NOT_BUILT canonicalization_test_NOT_BUILT)
endif()
