if(EXISTS "/home/cat/longfellow-zk/build-verifier/circuits/logic/bit_plucker_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-verifier/circuits/logic/bit_plucker_test[1]_tests.cmake")
else()
  add_test(bit_plucker_test_NOT_BUILT bit_plucker_test_NOT_BUILT)
endif()
