add_test([=[Transcript.Write]=]  /home/cat/longfellow-zk/clang-build-release/random/transcript_test [==[--gtest_filter=Transcript.Write]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Transcript.Write]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/random SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Transcript.TwoBlocks]=]  /home/cat/longfellow-zk/clang-build-release/random/transcript_test [==[--gtest_filter=Transcript.TwoBlocks]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Transcript.TwoBlocks]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/random SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Transcript.Associative]=]  /home/cat/longfellow-zk/clang-build-release/random/transcript_test [==[--gtest_filter=Transcript.Associative]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Transcript.Associative]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/random SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Transcript.TestVectors]=]  /home/cat/longfellow-zk/clang-build-release/random/transcript_test [==[--gtest_filter=Transcript.TestVectors]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Transcript.TestVectors]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/random SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Transcript.TestVec]=]  /home/cat/longfellow-zk/clang-build-release/random/transcript_test [==[--gtest_filter=Transcript.TestVec]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Transcript.TestVec]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/random SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  transcript_test_TESTS Transcript.Write Transcript.TwoBlocks Transcript.Associative Transcript.TestVectors Transcript.TestVec)
