if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/mdoc/mdoc_signature_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/mdoc/mdoc_signature_test[1]_tests.cmake")
else()
  add_test(mdoc_signature_test_NOT_BUILT mdoc_signature_test_NOT_BUILT)
endif()
