if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/tests/base64/decode_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/tests/base64/decode_test[1]_tests.cmake")
else()
  add_test(decode_test_NOT_BUILT decode_test_NOT_BUILT)
endif()
