if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/tests/jwt/jwt_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/tests/jwt/jwt_test[1]_tests.cmake")
else()
  add_test(jwt_test_NOT_BUILT jwt_test_NOT_BUILT)
endif()
