add_test([=[ecdsa.verify3_p256]=]  /home/cat/longfellow-zk/build-verifier/circuits/ecdsa/verify_test [==[--gtest_filter=ecdsa.verify3_p256]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ecdsa.verify3_p256]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/ecdsa SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ecdsa.p256_failure]=]  /home/cat/longfellow-zk/build-verifier/circuits/ecdsa/verify_test [==[--gtest_filter=ecdsa.p256_failure]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ecdsa.p256_failure]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/ecdsa SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ECDSA.prover_verifier3_p256]=]  /home/cat/longfellow-zk/build-verifier/circuits/ecdsa/verify_test [==[--gtest_filter=ECDSA.prover_verifier3_p256]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ECDSA.prover_verifier3_p256]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/ecdsa SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ECDSA.Size]=]  /home/cat/longfellow-zk/build-verifier/circuits/ecdsa/verify_test [==[--gtest_filter=ECDSA.Size]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ECDSA.Size]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/ecdsa SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  verify_test_TESTS ecdsa.verify3_p256 ecdsa.p256_failure ECDSA.prover_verifier3_p256 ECDSA.Size)
