add_test([=[MSO.Example2]=]  /home/cat/longfellow-zk/build-verifier/circuits/cbor_parser/mso2_test [==[--gtest_filter=MSO.Example2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MSO.Example2]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/cbor_parser SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MSO.Various]=]  /home/cat/longfellow-zk/build-verifier/circuits/cbor_parser/mso2_test [==[--gtest_filter=MSO.Various]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MSO.Various]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/cbor_parser SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MSO.MapLookup]=]  /home/cat/longfellow-zk/build-verifier/circuits/cbor_parser/mso2_test [==[--gtest_filter=MSO.MapLookup]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MSO.MapLookup]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/cbor_parser SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MSO.Example2Real]=]  /home/cat/longfellow-zk/build-verifier/circuits/cbor_parser/mso2_test [==[--gtest_filter=MSO.Example2Real]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MSO.Example2Real]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/cbor_parser SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  mso2_test_TESTS MSO.Example2 MSO.Various MSO.MapLookup MSO.Example2Real)
