if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/compiler/compiler_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/compiler/compiler_test[1]_tests.cmake")
else()
  add_test(compiler_test_NOT_BUILT compiler_test_NOT_BUILT)
endif()
