add_test([=[MdocZKTest.one_claim]=]  /home/cat/longfellow-zk/build-verifier/circuits/mdoc/mdoc_zk_test [==[--gtest_filter=MdocZKTest.one_claim]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MdocZKTest.one_claim]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/mdoc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MdocZKTest.long_attribute]=]  /home/cat/longfellow-zk/build-verifier/circuits/mdoc/mdoc_zk_test [==[--gtest_filter=MdocZKTest.long_attribute]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MdocZKTest.long_attribute]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/mdoc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MdocZKTest.two_claims]=]  /home/cat/longfellow-zk/build-verifier/circuits/mdoc/mdoc_zk_test [==[--gtest_filter=MdocZKTest.two_claims]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MdocZKTest.two_claims]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/mdoc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MdocZKTest.wrong_witness]=]  /home/cat/longfellow-zk/build-verifier/circuits/mdoc/mdoc_zk_test [==[--gtest_filter=MdocZKTest.wrong_witness]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MdocZKTest.wrong_witness]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/mdoc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MdocZKTest.bad_arguments]=]  /home/cat/longfellow-zk/build-verifier/circuits/mdoc/mdoc_zk_test [==[--gtest_filter=MdocZKTest.bad_arguments]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MdocZKTest.bad_arguments]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/mdoc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MdocZKTest.attr_mismatch]=]  /home/cat/longfellow-zk/build-verifier/circuits/mdoc/mdoc_zk_test [==[--gtest_filter=MdocZKTest.attr_mismatch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MdocZKTest.attr_mismatch]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/mdoc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MdocZKTest.bad_proofs]=]  /home/cat/longfellow-zk/build-verifier/circuits/mdoc/mdoc_zk_test [==[--gtest_filter=MdocZKTest.bad_proofs]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MdocZKTest.bad_proofs]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/mdoc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircuitGenerationTest.attempt_to_generate_old_circuit]=]  /home/cat/longfellow-zk/build-verifier/circuits/mdoc/mdoc_zk_test [==[--gtest_filter=CircuitGenerationTest.attempt_to_generate_old_circuit]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircuitGenerationTest.attempt_to_generate_old_circuit]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/mdoc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CborValidate.ValidInputs]=]  /home/cat/longfellow-zk/build-verifier/circuits/mdoc/mdoc_zk_test [==[--gtest_filter=CborValidate.ValidInputs]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CborValidate.ValidInputs]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/mdoc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CborValidate.InvalidInputs]=]  /home/cat/longfellow-zk/build-verifier/circuits/mdoc/mdoc_zk_test [==[--gtest_filter=CborValidate.InvalidInputs]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CborValidate.InvalidInputs]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/mdoc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  mdoc_zk_test_TESTS MdocZKTest.one_claim MdocZKTest.long_attribute MdocZKTest.two_claims MdocZKTest.wrong_witness MdocZKTest.bad_arguments MdocZKTest.attr_mismatch MdocZKTest.bad_proofs CircuitGenerationTest.attempt_to_generate_old_circuit CborValidate.ValidInputs CborValidate.InvalidInputs)
