if(EXISTS "/home/cat/longfellow-zk/build-demo-cli/sumcheck/sumcheck_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-demo-cli/sumcheck/sumcheck_test[1]_tests.cmake")
else()
  add_test(sumcheck_test_NOT_BUILT sumcheck_test_NOT_BUILT)
endif()
