if(EXISTS "/home/cat/longfellow-zk/build-demo-cli/circuits/tests/sha3/sha3_circuit_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-demo-cli/circuits/tests/sha3/sha3_circuit_test[1]_tests.cmake")
else()
  add_test(sha3_circuit_test_NOT_BUILT sha3_circuit_test_NOT_BUILT)
endif()
