if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/examples/anoncred/anoncred_demo_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/examples/anoncred/anoncred_demo_test[1]_tests.cmake")
else()
  add_test(anoncred_demo_test_NOT_BUILT anoncred_demo_test_NOT_BUILT)
endif()
