add_test([=[MAC.full_circuit_test_128]=]  /home/cat/longfellow-zk/build-verifier/circuits/mac/mac_circuit_test [==[--gtest_filter=MAC.full_circuit_test_128]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MAC.full_circuit_test_128]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/mac SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[MAC.full_circuit_GF2_128]=]  /home/cat/longfellow-zk/build-verifier/circuits/mac/mac_circuit_test [==[--gtest_filter=MAC.full_circuit_GF2_128]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[MAC.full_circuit_GF2_128]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/mac SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  mac_circuit_test_TESTS MAC.full_circuit_test_128 MAC.full_circuit_GF2_128)
