if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/tests/mdoc/mdoc_1f_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/circuits/tests/mdoc/mdoc_1f_test[1]_tests.cmake")
else()
  add_test(mdoc_1f_test_NOT_BUILT mdoc_1f_test_NOT_BUILT)
endif()
