if(EXISTS "/home/cat/longfellow-zk/build-demo-cli/util/ceildiv_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-demo-cli/util/ceildiv_test[1]_tests.cmake")
else()
  add_test(ceildiv_test_NOT_BUILT ceildiv_test_NOT_BUILT)
endif()
