if(EXISTS "/home/cat/longfellow-zk/clang-build-release/ligero/ligero_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/clang-build-release/ligero/ligero_test[1]_tests.cmake")
else()
  add_test(ligero_test_NOT_BUILT ligero_test_NOT_BUILT)
endif()
