add_test([=[Ligero.Fp]=]  /home/cat/longfellow-zk/clang-build-release/ligero/ligero_test [==[--gtest_filter=Ligero.Fp]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Ligero.Fp]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/ligero SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Ligero.GF2_128]=]  /home/cat/longfellow-zk/clang-build-release/ligero/ligero_test [==[--gtest_filter=Ligero.GF2_128]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Ligero.GF2_128]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/ligero SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  ligero_test_TESTS Ligero.Fp Ligero.GF2_128)
