if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/crt_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/crt_test[1]_tests.cmake")
else()
  add_test(crt_test_NOT_BUILT crt_test_NOT_BUILT)
endif()
