if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/fft_interpolation_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/fft_interpolation_test[1]_tests.cmake")
else()
  add_test(fft_interpolation_test_NOT_BUILT fft_interpolation_test_NOT_BUILT)
endif()
