if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/fp_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/fp_test[1]_tests.cmake")
else()
  add_test(fp_test_NOT_BUILT fp_test_NOT_BUILT)
endif()
