if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/limb_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/limb_test[1]_tests.cmake")
else()
  add_test(limb_test_NOT_BUILT limb_test_NOT_BUILT)
endif()
