if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/nat_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/nat_test[1]_tests.cmake")
else()
  add_test(nat_test_NOT_BUILT nat_test_NOT_BUILT)
endif()
