if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/nussbaumer_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/nussbaumer_test[1]_tests.cmake")
else()
  add_test(nussbaumer_test_NOT_BUILT nussbaumer_test_NOT_BUILT)
endif()
