if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/nussbaumerfp2_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/nussbaumerfp2_test[1]_tests.cmake")
else()
  add_test(nussbaumerfp2_test_NOT_BUILT nussbaumerfp2_test_NOT_BUILT)
endif()
