if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/poly_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/poly_test[1]_tests.cmake")
else()
  add_test(poly_test_NOT_BUILT poly_test_NOT_BUILT)
endif()
