if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/rfft_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/rfft_test[1]_tests.cmake")
else()
  add_test(rfft_test_NOT_BUILT rfft_test_NOT_BUILT)
endif()
