if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/sysdep_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/sysdep_test[1]_tests.cmake")
else()
  add_test(sysdep_test_NOT_BUILT sysdep_test_NOT_BUILT)
endif()
