if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/utility_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/algebra/utility_test[1]_tests.cmake")
else()
  add_test(utility_test_NOT_BUILT utility_test_NOT_BUILT)
endif()
