if(EXISTS "/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/random/random_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/BaisWork/longfellow-zk/build-mac/random/random_test[1]_tests.cmake")
else()
  add_test(random_test_NOT_BUILT random_test_NOT_BUILT)
endif()
