if(EXISTS "/Users/cnxf/信安赛/代理签名/translated_atrps/code/longfellow-zk/build-delegation/circuits/tests/base64/decode_circuit_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/代理签名/translated_atrps/code/longfellow-zk/build-delegation/circuits/tests/base64/decode_circuit_test[1]_tests.cmake")
else()
  add_test(decode_circuit_test_NOT_BUILT decode_circuit_test_NOT_BUILT)
endif()
