if(EXISTS "/home/cat/longfellow-zk/build-demo-cli/circuits/logic/polynomial_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-demo-cli/circuits/logic/polynomial_test[1]_tests.cmake")
else()
  add_test(polynomial_test_NOT_BUILT polynomial_test_NOT_BUILT)
endif()
