if(EXISTS "/home/cat/longfellow-zk/build-demo-cli/circuits/logic/routing_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-demo-cli/circuits/logic/routing_test[1]_tests.cmake")
else()
  add_test(routing_test_NOT_BUILT routing_test_NOT_BUILT)
endif()
