add_test([=[jwt.EvalJWT]=]  /home/cat/longfellow-zk/build-verifier/circuits/tests/mdoc/mdoc_1f_test [==[--gtest_filter=jwt.EvalJWT]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[jwt.EvalJWT]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/tests/mdoc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mdoc1fTest.RunsExamples]=]  /home/cat/longfellow-zk/build-verifier/circuits/tests/mdoc/mdoc_1f_test [==[--gtest_filter=Mdoc1fTest.RunsExamples]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mdoc1fTest.RunsExamples]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/tests/mdoc SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  mdoc_1f_test_TESTS jwt.EvalJWT Mdoc1fTest.RunsExamples)
