add_test([=[jwt.EvalJWT]=]  /home/cat/longfellow-zk/clang-build-release/circuits/tests/jwt/jwt_test [==[--gtest_filter=jwt.EvalJWT]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[jwt.EvalJWT]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/circuits/tests/jwt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[jwt.EvalFailureJWT]=]  /home/cat/longfellow-zk/clang-build-release/circuits/tests/jwt/jwt_test [==[--gtest_filter=jwt.EvalFailureJWT]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[jwt.EvalFailureJWT]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/circuits/tests/jwt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[jwt.JwtZk7]=]  /home/cat/longfellow-zk/clang-build-release/circuits/tests/jwt/jwt_test [==[--gtest_filter=jwt.JwtZk7]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[jwt.JwtZk7]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/circuits/tests/jwt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[jwt.JwtZk9]=]  /home/cat/longfellow-zk/clang-build-release/circuits/tests/jwt/jwt_test [==[--gtest_filter=jwt.JwtZk9]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[jwt.JwtZk9]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/circuits/tests/jwt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[jwt.JwtZk11]=]  /home/cat/longfellow-zk/clang-build-release/circuits/tests/jwt/jwt_test [==[--gtest_filter=jwt.JwtZk11]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[jwt.JwtZk11]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/circuits/tests/jwt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[jwt.JwtZk13]=]  /home/cat/longfellow-zk/clang-build-release/circuits/tests/jwt/jwt_test [==[--gtest_filter=jwt.JwtZk13]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[jwt.JwtZk13]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/clang-build-release/circuits/tests/jwt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  jwt_test_TESTS jwt.EvalJWT jwt.EvalFailureJWT jwt.JwtZk7 jwt.JwtZk9 jwt.JwtZk11 jwt.JwtZk13)
