if(EXISTS "/home/cat/longfellow-zk/build-demo-cli/arrays/affine_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-demo-cli/arrays/affine_test[1]_tests.cmake")
else()
  add_test(affine_test_NOT_BUILT affine_test_NOT_BUILT)
endif()
