if(EXISTS "/home/cat/longfellow-zk/build-demo-cli/arrays/eqs_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-demo-cli/arrays/eqs_test[1]_tests.cmake")
else()
  add_test(eqs_test_NOT_BUILT eqs_test_NOT_BUILT)
endif()
