if(EXISTS "/home/cat/longfellow-zk/clang-build-release/circuits/tests/mdoc/mdoc_revocation_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/clang-build-release/circuits/tests/mdoc/mdoc_revocation_test[1]_tests.cmake")
else()
  add_test(mdoc_revocation_test_NOT_BUILT mdoc_revocation_test_NOT_BUILT)
endif()
