if(EXISTS "/Users/cnxf/信安赛/代理签名/translated_atrps/code/longfellow-zk/build-delegation/algebra/poly_test[1]_tests.cmake")
  include("/Users/cnxf/信安赛/代理签名/translated_atrps/code/longfellow-zk/build-delegation/algebra/poly_test[1]_tests.cmake")
else()
  add_test(poly_test_NOT_BUILT poly_test_NOT_BUILT)
endif()
