add_test([=[Sha3Reference.TestVec]=]  /home/cat/longfellow-zk/build-verifier/circuits/tests/sha3/sha3_reference_test [==[--gtest_filter=Sha3Reference.TestVec]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Sha3Reference.TestVec]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/tests/sha3 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Sha3Reference.OneMillionAs]=]  /home/cat/longfellow-zk/build-verifier/circuits/tests/sha3/sha3_reference_test [==[--gtest_filter=Sha3Reference.OneMillionAs]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Sha3Reference.OneMillionAs]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/tests/sha3 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Sha3Reference.Shake128Test]=]  /home/cat/longfellow-zk/build-verifier/circuits/tests/sha3/sha3_reference_test [==[--gtest_filter=Sha3Reference.Shake128Test]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Sha3Reference.Shake128Test]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/tests/sha3 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Sha3Reference.Shake256Test]=]  /home/cat/longfellow-zk/build-verifier/circuits/tests/sha3/sha3_reference_test [==[--gtest_filter=Sha3Reference.Shake256Test]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Sha3Reference.Shake256Test]=]  PROPERTIES WORKING_DIRECTORY /home/cat/longfellow-zk/build-verifier/circuits/tests/sha3 SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  sha3_reference_test_TESTS Sha3Reference.TestVec Sha3Reference.OneMillionAs Sha3Reference.Shake128Test Sha3Reference.Shake256Test)
