if(EXISTS "/home/cat/longfellow-zk/build-bringup/circuits/tests/base64/decode_circuit_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-bringup/circuits/tests/base64/decode_circuit_test[1]_tests.cmake")
else()
  add_test(decode_circuit_test_NOT_BUILT decode_circuit_test_NOT_BUILT)
endif()
