if(EXISTS "/home/cat/longfellow-zk/build-bringup/circuits/mdoc/mdoc_signature_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-bringup/circuits/mdoc/mdoc_signature_test[1]_tests.cmake")
else()
  add_test(mdoc_signature_test_NOT_BUILT mdoc_signature_test_NOT_BUILT)
endif()
