if(EXISTS "/home/cat/longfellow-zk/build-verifier/proto/circuit_test[1]_tests.cmake")
  include("/home/cat/longfellow-zk/build-verifier/proto/circuit_test[1]_tests.cmake")
else()
  add_test(circuit_test_NOT_BUILT circuit_test_NOT_BUILT)
endif()
